FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base 
WORKDIR /app 
EXPOSE 80 

ENV BACKEND_URL=http://recommendation:5190/api/getDataFromTableWithFilter

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build 
WORKDIR /src 

COPY . . 
RUN dotnet restore "ApiGateway.csproj" 
RUN dotnet build "ApiGateway.csproj" -c Release -o /app/build 
 
FROM build AS publish 
RUN dotnet publish "ApiGateway.csproj" -c Release -o /app/publish 
 
FROM base AS final 
WORKDIR /app 
COPY --from=publish /app/publish . 
ENTRYPOINT ["dotnet", "ApiGateway.dll"]